
# File di configurazione

[COMMON]


[DATI1D]
cartella = /home/cfmi.arpal.org/daniele.carnevale/Scrivania/MeteoBricchi/dati1D


[DATI2D]
cartella = /home/cfmi.arpal.org/daniele.carnevale/Scrivania/MeteoBricchi/dati2D
# cartella = /media/daniele/Daniele2TB/repo/MeteoBricchi/dati2D
